# fly.toml app configuration file generated for hazel-worker on 2023-11-20T00:41:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hazel-worker"
primary_region = "ams"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
