# fly.toml app configuration file generated for lago-web on 2023-10-09T19:04:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lago-web"
primary_region = "ams"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
