import { fontMono, fontSans } from "@/lib/fonts"

import "./globals.css"

import { cn } from "@/lib/utils"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable, fontMono.variable)}>
				{children}
			</body>
		</html>
	)
}
