[package]
version = "0.1.0"
edition = "2021"
name = "hazelflux"
authors = ["HazelHook"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.0.15"
jsonschema = { version = "*", default-features = false, features = ["structopt"]}
serde_json = { version = "1.0", features = ["raw_value"]}
serde = { version = "1.0", features = ["derive"] }

[profile.dev]
lto = true
strip = true
codegen-units = 1
