name = "hazel-backend"
compatibility_date = "2023-01-01"
services = [
  { binding = "HAZELFLUX_BINDING", service = "hazelflux", environment = "production" }
]

[vars]
PLANETSCALE_DB_HOST="aws.connect.psdb.cloud"
PLANETSCALE_DB_USERNAME="9w2ih1tzb2r6f96saadh"
PLANETSCALE_DB_PASSWORD="pscale_pw_YuVALk0njR6Q1EjVZPZevOTvFaJHSh8E47YxUfxEHj2"
TINY_TOKEN = "p.eyJ1IjogImI2MTNjZDdkLTFmZDItNDNlOS1hNzA5LTZhZTQ0NmI3ZjMxMSIsICJpZCI6ICI1NjJkMWRmOC0yZGQ3LTQ2YmUtODcxYS05OTEyZWQ4MzMwNDIifQ.DI8E73IYinRTBH2_XbjwMvzMSzR_qPlROoaAhhOSa-0"


[placement]
mode = "smart"
