# fly.toml app configuration file generated for lago-pdf-gen on 2023-10-10T01:14:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lago-pdf-gen"
primary_region = "ams"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
