name: Deploy Prod
on:
  push:
    branches:
      - production
jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --dockerfile ./apps/api/Dockerfile --config apps/api/fly.toml 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --dockerfile ./apps/backend/Dockerfile --config apps/backend/fly.toml 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-worker:
    name: Deploy Worker
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --local-only --dockerfile ./apps/worker/Dockerfile --config apps/worker/fly.toml 
          env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-lago:
      name: Deploy Lago
      runs-on: ubuntu-latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      steps:
            - uses: actions/checkout@v3
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --local-only ./fly/lago/api 
            - run: flyctl deploy --local-only ./fly/lago/pdf 
            - run: flyctl deploy --local-only ./fly/lago/web 
              
    
